# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 7d4ac94fd6a30a519d0d73f6b12bd870ba354f4a40fcd7ee389a92e1c63e3cced786dc690dedfb1eb6cbbc081551eb27f50ff78d2d9cf9c25729cbdcff9dc380

test:
  domain_name: example.com 
  secret_key_base: a2f4a87c63efd7669781a7d7b49969426d01d473256bc2b11b455a26bb47fa37c126a2473414c64c1a545f8c27977892d793bcc116f48b0796610f203f5e0b02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
